# -*- coding: utf-8 -*-
"""autocorrect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FzbMhJbL2vV6-cGNjrh6hCxYVJfFldhH
"""

!pip install rapidfuzz

import time
import csv
import random
from rapidfuzz import process

# Lists of correct and incorrect words
fruits_correct = ["apple", "banana", "cherry", "mango", "Tender Coconut ","Nariyal Pani",
    "Brown Coconut"," Nariyal",
    "Papaya ","Papita",
    "Water Chestnut"," Singhara "," Paniphal",
    "Small Kashmiri Apple"," Kashmiri Apple",
    "Kashmiri Apple",
    "Pomegranate "," Anaar",
    "Guava ","Amrud",
    "Sugarcane Stick"," Ganna",
    "Pomegranate Small"
    "Kashmiri Apple","kashmiri  sev"
    "Pomegranate Medium Anaar",
    "Guava ","Amrud",
    "Sugarcane Stick"," Ganna",
    "Pomegranate Small",
    "Kiran Watermelon",
    "Black Grapes",
    "Sweet Tamarind Box Imli",
    "Kinnaur Apple",
    "Shimla Apple Seb",
    "Queen Pineapple"," Ananas",
    "Groundnut ","Moongfali",
    "Sun Melon"," Sarda",
    "Apple Ber",
    "Green Grapes",
    "Chikoo Sapota",
    "Strawberry",
    "Green Kiwi",
    "Thai Guava","amrud"
    "Coconut Chunks",
    "Red Globe Grapes",
    "Persimmon Ramphal",
    "Pomegranate Peeled",
    "New Zealand Royal Gala Apple",
    "Pineapple Cut",
    "Red Delicious Apple",
    "Custard Apple",
    "Turkey Royal Gala Apple",
    "Valencia Orange",
    "Fuji Apple From New Zealand Seb",
    "Plum Aloo Bukhara ",
    "Dried Apricots",
    "Washington Red Delicious Apple",
    "Fuji Apple Imported",
    "Pear Beauty South Africa",
    "Banana",
    "Baby Banana",
    "Nagpur Orange",
    "Small Shimla Apple Seb",
    "Assorted Fruits Panch Phal",
    "Sweet Lime Mosambi",
    "Nagpur Orange Regular",
    "Pear Nashpati Himachal",
    "Pineapple",
    "Pomegranate Large",
    "Raw Mango",
    "Avocado Tanzania",
    "Blueberry Peru",
    "Dragon Fruit"]

fruits_incorrect = ["applle", "banana", "cherrry", "mango", "Tender Coconut ","Nariyal Paani",
    "Brown Cocoonut"," Nariyal",
    "Papaya ","Papitaa",
    "Water Chesnut"," Singhara "," Paniphall",
    "Small Kashmiri Aple"," Kashmiri Aple",
    "Kashmiri Applle",
    "Pomegranat "," Anar",
    "Guvaa ","Amrud",
    "Sugercane Stick"," Ganna",
    "Pomergranate Small"
    "Kashmiiri Apple","kashmiri  sevv"
    "Pomegranate Medum Anaar",
    "Guaa ","Amrrud",
    "Sugarcane Stick"," Gana",
    "Pomegrante Small",
    "Kiran Watermelonn",
    "Black Grapees",
    "Sweet Tamarind Box Imlie",
    "Kinnaaur Apple",
    "Shimla Appl Seb",
    "Quueen Pineapple"," Annanas",
    "Groundnutt ","Moongphali",
    "Sun Melon"," Sardaa",
    "Appple Ber",
    "Green Grapess",
    "Chikoo Sapotaa",
    "Strawbery",
    "Green Kiwwi",
    "Thai Guwaa","amrud"
    "Cocunut Chunks",
    "Red Globe Grapes",
    "Persimmon Rampal",
    "Pomgranate Peeled",
    "New Zeland Royal Gala Apple",
    "Pineaple Cut",
    "Red Delicous Apple",
    "Custard Aple",
    "Turkey Royale Gala Apple",
    "Valencia Orannge",
    "Fuji Apple From New Zeealand Seb",
    "Plumm Aloo Bukhara ",
    "Dried Apricot",
    "Washingto Red Delicious Apple",
    "Fujii Apple Imported",
    "Peaar Beauty South Africa",
    "Bananna",
    "Baby Baanana",
    "Nagpur Orrange",
    "Small Shimla Aple Seb",
    "Assorted Fruits Panchh Phal",
    "Sweet Lime Mosambi",
    "Nagppur Orange Regular",
    "Pear Nasphati Himachal",
    "Pinepple",
    "Pomegranet Large",
    "Raw Mangoo",
    "Avocaddo Tanzania",
    "Bluebery Peru",
    "Draggon Fruit"]

vegetables_correct = ["Carrot", "Potato", "Onion", "Tomato", "Spinach",
    "Cucumber", "Broccoli", "Cauliflower", "Bell pepper", "Lettuce", "Desi Tomato "," Tamatar",
    "Onion " ,"Pyaz",
    "Green Chilli"," Hari Mirch",
    "Ginger", "Adrak",
    "Potato," "Aloo",
    "Green Capsicum"," Shimla Mirch",
    "Green Cucumber"," Kheera",
    "Lemon"," Nimbu",
    "Lady Finger","Bhindi",
    "Button Mushroom",
    "Garlic"," Lehsun",
    "Hybrid Tomato ","Tamatar",
    "Cabbage ","Patta Gobhi",
    "Beetroot"," Chukandar",
    "Bottle Gourd ","Lauki",
    "Red Carrot"," Gajar",
    "French Beans",
    " Cucumber"," Kheera",
    "Radish ","Mooli",
    "Baby Bottle Gourd"," Lauki",
    "Pointed Gourd ","Parwal",
    "Green Peas"," Matar",
    "Sweet Potato"," Shakarkandi",
    "Brinjal Bharta"," Baingan",
    "Raw Turmeric"," Kachhi Haldi",
    "Baby Onion"," Sirka Pyaz",
    "Ivy Gourd"," Kundru",
    "Sponge Gourd"," Tori",
    "Bitter Gourd"," Karela",
    "Broad Beans"," Sem Phali",
    "Cowpea Beans"," Lobia Phali",
    "Long Purple"," Brinjal Baingan",
    "Picador Chilli ","Achari Mirch",
    "Raw Banana ","Kacha Kela",
    "Round Bottle Gourd ","Gol Lauki",
    "Cauliflower ","Phool Gobhi",
    "Turnip ","Shalgam",
    "Coriander Bunch"," Dhaniya Patta",
    "Broccoli",
    "Green ","Lettuce",
    "Sweet Corn",
    "Red Bell Pepper",
    "Spinach"," Palak",
    "Baby Corn",
    "Yellow Bell Pepper",
    "Yam",
    "Spring Onion ","Hari Pyaz",
    "Desi Kateri Spinach"," Palak",
    "Curry Leaves"," Kadi Patta",
    "Mustard Leaves"," Sarso Saag",
    "Chenopodium"," Bathua",
    "Green"," Zucchini",
    "Jackfruit ","Kathal",
    "Mint Leaves"," Pudina",
    "Kale Leaves"]

vegetables_incorrect = ["Carrrot", "Potato", "Onnion", "Tommato", "Spinich",
    "Cucummber", "Brocoli", "Cauliffower", "Bell pepper", "Letttuce", "Desi Tomato "," Tamattar",
    "Onion " ,"Piaz",
    "Green Chilli"," Hari Mircch",
    "Ginnger", "Adrak",
    "Potato," "Aloo",
    "Green Capssicum"," Shimla Mirch",
    "Green Cucumber"," Kheeraa",
    "Lemmon"," Nimbu",
    "Lady Fingerr","Bhindi",
    "Button Mushrroom",
    "Garlic"," Lehsuun",
    "Hybrid Tomato ","Tamattar",
    "Cabbage ","Patta Gobhi",
    "Beettroot"," Chukandar",
    "Botttle Gourd ","Lauki",
    "Red Carrrot"," Gajar",
    "Frrench Beans",
    " Cucumber"," Kheera",
    "Raddish ","Mooli",
    "Baby Bottle Gourd"," Laukki",
    "Pointed Gourd ","Parwal",
    "Green Ppeas"," Matar",
    "Sweet Potato"," Shakarkanddi",
    "Brinjal Bharta"," Baiingan",
    "Raw Turrmeric"," Kachhi Haldi",
    "Baby Onion"," Sirka Piaz",
    "Ivy Gourrd"," Kundru",
    "Sponge Gourrd"," Tori",
    "Bitter Gourrd"," Karela",
    "Broadd Beans"," Sem Phali",
    "Cowpea Beans"," Lobia Phali",
    "Long Purple"," Brinjal Baingan",
    "Picador Chilli ","Achaari Mirch",
    "Raw Bannana ","Kacha Kela",
    "Round Bottle Gourd ","Gol Lauki",
    "Caulliflower ","Phool Gobhi",
    "Turnip ","Shalggam",
    "Coriander Bunch"," Dhaniya Patta",
    "Broccoli",
    "Green ","Letttuce",
    "Sweet Corn",
    "Red Bell Pepper",
    "Spinach"," Pallak",
    "Baby Corn",
    "Yellow Bell Pepper",
    "Yam",
    "Spring Onion ","Hari Piyaz",
    "Desi Kateri Spinach"," Palak",
    "Curry Leaves"," Kadi Patta",
    "Mustard Leaves"," Sarrso Saag",
    "Chenopodiumm"," Bathua",
    "Green"," Zuchhini",
    "Jackfruit ","Katthal",
    "Mint Leaves"," Pudina",
    "Kale Leavess"]

cereals_correct = ["rice", "wheat", "corn","Daawat Biryani Basmati Rice Long Grains",
    "Daawat Rozana Super Basmati Rice",
    "India Gate Everyday Basmati Rice",
    "India Gate Super Basmati Rice",
    "India Gate Rozana Basmati Rice",
    "Whole Farm Premium Parmal Rice",
    "India Gate Dubar Basmati Rice",
    "India Gate Super Basmati Rice 1 kg + 500 g",
    "India Gate Rozana Pure Basmati Rice",
    "India Gate Mogra Basmati Rice Broken",
    "Daawat Rozana Mini Mogra Basmati Rice Broken",
    "India Gate Mini Mogra Basmati Rice Broken",
    "Whole Farm Premium Puffed Rice",
    "Daawat Super Basmati Rice Fluffy Long Grains",
    "Daawat Rozana Gold Basmati Rice",
    "India Gate Mini II Mogra Basmati Rice Broken",
    "India Gate Tibar Basmati Rice",
    "Agro Delight Steam Masuri Rice",
    "Fortune Hamesha Mini Dubar Basmati Rice",
    "Daawat Pulav Basmati Rice Slender Grains",
    "Fortune Biryani Special Extra Long Grain Basmati Rice",
    "India Gate Daily Premium Basmati Rice",
    "Whole Farm Premium Biryani Basmati Rice Long Grain",
    "Daawat Devaaya Everyday Basmati Rice",
    "Agro Delight Shakkar Chinni Rice",
    "India Gate Daily Delight Pure Basmati Rice Broken",
    "Whole Farm Premium Golden Sella Basmati Rice",
    "Diat Gud Karbs Govindo Bhog Rice",
    "Whole Farm Grocery Broken Mogra Basmati Rice",
    "India Gate Regular Choice Basmati Rice",
    "Daawat Devaaya Basmati Rice Aromatic Long & Fluffy",
    "Agro Delight Sambha Masuri Rice",
    "Whole Farm Grocery Raw Sonamasuri Rice 6-12 months Old",
    "Whole Farm Premium Brown Rice",
    "Daawat Biryani Basmati Rice ",
    "Pansari Daily Dubar Basmati Rice",
    "Diat Mogra Basmati Rice Broken Rice"]

cereals_incorrect = ["rce", "wheet", "cornn","Daawat Biryani Basmatty Rice Long Grains",
    "Daawat Rozana Super Basmati Ricce",
    "India Gatte Everyday Basmati Rice",
    "India Gatte Super Basmati Rice",
    "India Gatte Rozana Basmati Rice",
    "Whole Farm Premium Parrmal Rice",
    "India Gate Duba Basmati Rice",
    "India Gate Super Basmaty Rice 1 kg + 500 g",
    "India Gate Rozana Puree Basmati Rice",
    "India Gate Mogra Basmatti Rice Broken",
    "Daawat Rozana Mini Mograa Basmati Rice Broken",
    "India Gate Miny Mogra Basmati Rice Broken",
    "Whole Farm Premiium Puffed Rice",
    "Daawat Super Basmati Rie Fluffy Long Grains",
    "Daawat Rozna Gold Basmati Rice",
    "India Gate Mini II Mogra Basmatty Rice Broken",
    "India Gate Tibarr Basmati Rice",
    "Agro Delight Steeam Masuri Rice",
    "Fortune Hamesha Mini Dubarr Basmati Rice",
    "Daawat Pulav Basmati Ricce Slender Grains",
    "Fortune Biryani Speciall Extra Long Grain Basmati Rice",
    "India Gate Daily Premiun Basmati Rice",
    "Whole Farm Premium Biryani Basmati Rice Long Grainn",
    "Daawat Devaaaya Everyday Basmati Rice",
    "Agro Delight Shakkar Chinnii Rice",
    "India Gate Daily Delight Pure Basmattii Rice Broken",
    "Whole Farm Premium Golden Sela Basmati Rice",
    "Diat Gud Karbs Govindoo Bhog Rice",
    "Whole Farm Grocery Brokken Mogra Basmati Rice",
    "India Gate Regular Choicee Basmati Rice",
    "Daawat Devaaya Basmatti Rice Aromatic Long & Fluffy",
    "Agro Delight Sambha Masuri Rcce",
    "Whole Farm Grocery Raww Sonamasuri Rice 6-12 months Old",
    "Whole Farm Premium Brrown Rice",
    "Daawat Biriyani Basmati Rice ",
    "Pansari Daaily Dubar Basmati Rice","Diat Mogra Basmati Rice Brokken Rice","ricce"]


measurements_correct = ["kg", "plate", "dozen"]
measurements_incorrect = ["kg", "pate", "dozeen"]

numbers_correct = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
numbers_incorrect = ["on", "twp", "tree", "fore", "fiev", "sxi", "sevven", "eigt", "nien", "tn"]

# Create correct phrases
phrases_correct = []
for item in fruits_correct + vegetables_correct + cereals_correct:
    for measurement in measurements_correct:
        for num in numbers_correct:
            phrases_correct.append(f"{num} {measurement} of {item}")

# Create incorrect phrases
phrases_incorrect = []
for item in fruits_incorrect + vegetables_incorrect + cereals_incorrect:
    for measurement in measurements_incorrect:
        for num in numbers_incorrect:
            phrases_incorrect.append(f"{num} {measurement} of {item}")

# # Limit to 5000 correct phrases and 10000 incorrect phrases
# phrases_correct = phrases_correct[:5000]
# phrases_incorrect = phrases_incorrect[:10000]

# Write CSV files
with open('correct_phrases.csv', 'w', newline='') as correct_file:
    writer = csv.writer(correct_file)
    writer.writerow(["Correct Phrases"])
    for phrase in phrases_correct:
        writer.writerow([phrase])

with open('incorrect_phrases.csv', 'w', newline='') as incorrect_file:
    writer = csv.writer(incorrect_file)
    writer.writerow(["Incorrect Phrases"])
    for phrase in phrases_incorrect:
        writer.writerow([phrase])

# Read CSV files
with open('correct_phrases.csv', newline='') as correct_file:
    reader = csv.reader(correct_file)
    next(reader)  # Skip header
    phrases_correct = [row[0] for row in reader]

with open('incorrect_phrases.csv', newline='') as incorrect_file:
    reader = csv.reader(incorrect_file)
    next(reader)  # Skip header
    phrases_incorrect = [row[0] for row in reader]

# Function to find the closest match using fuzzywuzzy
def find_closest_match(incorrect_phrase, correct_phrases):
    match = process.extractOne(incorrect_phrase, correct_phrases)
    return match[0] if match else None

start_time = time.time()

corrected_phrases = []  # List to store the corrected phrases
for phrase in phrases_incorrect:
    corrected_phrase = find_closest_match(phrase, phrases_correct)
    corrected_phrases.append(corrected_phrase if corrected_phrase else "No match")

matching_time = time.time() - start_time
# Measure accuracy
correct_matches = 0
for i in range(len(phrases_correct)):
    if corrected_phrases[i] == phrases_correct[i]:
        correct_matches += 1

accuracy = (correct_matches / len(corrected_phrases)) * 100

# Print the efficiency results and accuracy
print(f"Time to match 10000 phrases: {matching_time:.4f} seconds ({matching_time/10000:.4f} secs per phrase)")
print(f"Accuracy of autocorrection: {accuracy:.2f}%")

# Optionally, print results for inspection (first 5)
print("\nSample Corrected Phrases:")
for i in range(5):
    print(f"Incorrect: {phrases_incorrect[i]} -> Corrected: {corrected_phrases[i]}")

# Write corrected phrases to CSV
with open('corrected_phrases.csv', 'w', newline='') as corrected_file:
    writer = csv.writer(corrected_file)
    writer.writerow(["Incorrect Phrases", "Corrected Phrases"])
    for incorrect_phrase, corrected_phrase in zip(phrases_incorrect, corrected_phrases):
        writer.writerow([incorrect_phrase, corrected_phrase])

